name: Perl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      uses: docker://perl:5.26
      with:
        args: "cpanm --quiet --installdeps --notest . && perl Build.PL && ./Build && ./Build test"

